//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class MonsterTriggerBase : JW_Table.Binary, JW_Table.IKey
{
	public partial class MonsterInfoDef : JW_Table.Binary
	{
		private int m_MonsterID;
		private int m_Level;
		private int m_AIDiff;
		private int m_Count;

		public int MonsterID
		{
			get { return m_MonsterID; }
			set { m_MonsterID = value; }
		}

		public int Level
		{
			get { return m_Level; }
			set { m_Level = value; }
		}

		public int AIDiff
		{
			get { return m_AIDiff; }
			set { m_AIDiff = value; }
		}

		public int Count
		{
			get { return m_Count; }
			set { m_Count = value; }
		}

		public override void Read(JW_Table.Reader reader)
		{
			m_MonsterID = reader.ReadInt32();
			m_Level = reader.ReadInt32();
			m_AIDiff = reader.ReadInt32();
			m_Count = reader.ReadInt32();
		}
	}

	public partial class MultiMonsterDef : JW_Table.Binary
	{
		private System.Collections.Generic.List<MonsterInfoDef> m_data = new System.Collections.Generic.List<MonsterInfoDef>();

		public System.Collections.Generic.List<MonsterInfoDef> data
		{
			get { return m_data; }
		}

		public override void Read(JW_Table.Reader reader)
		{
			m_data = reader.ReadRepeatedItem(m_data);
		}
	}

	private int m_ID;
	private MultiMonsterDef m_MonsterInfo;

	public int ID
	{
		get { return m_ID; }
		set { m_ID = value; }
	}

	public MultiMonsterDef MonsterInfo
	{
		get { return m_MonsterInfo; }
		set { m_MonsterInfo = value; }
	}

	public long Key()
	{
		return m_ID;
	}

	public override void Read(JW_Table.Reader reader)
	{
		m_ID = reader.ReadInt32();
		m_MonsterInfo = reader.ReadItem<MultiMonsterDef>();
	}
}

//MonsterTriggerBase.xlsx
public sealed class MonsterTriggerBaseManager : JW_Table.TableManager<MonsterTriggerBase>
{
	public const uint VERSION = 156707264;

	private MonsterTriggerBaseManager()
	{
	}

	private static readonly MonsterTriggerBaseManager ms_instance = new MonsterTriggerBaseManager();

	public static MonsterTriggerBaseManager instance
	{
		get { return ms_instance; }
	}

	public string source
	{
		get { return "MonsterTriggerBase.tbl"; }
	}

	public bool Load(string path)
	{
		return Load(path, source, VERSION);
	}

	public bool Load(byte[] buffer)
	{
		return Load(buffer, VERSION, source);
	}

	public MonsterTriggerBase Find(int key)
	{
		return FindInternal(key);
	}
}
