//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class SkillBase : JW_Table.Binary, JW_Table.IKey
{
	private int m_ID;
	private string m_Name;
	private string m_Icon;
	private string m_Action;
	private string m_Desc;
	private int m_TreeType;

	public int ID
	{
		get { return m_ID; }
		set { m_ID = value; }
	}

	public string Name
	{
		get { return m_Name; }
		set { m_Name = value; }
	}

	public string Icon
	{
		get { return m_Icon; }
		set { m_Icon = value; }
	}

	public string Action
	{
		get { return m_Action; }
		set { m_Action = value; }
	}

	public string Desc
	{
		get { return m_Desc; }
		set { m_Desc = value; }
	}

	public int TreeType
	{
		get { return m_TreeType; }
		set { m_TreeType = value; }
	}

	public long Key()
	{
		return m_ID;
	}

	public override void Read(JW_Table.Reader reader)
	{
		m_ID = reader.ReadInt32();
		m_Name = reader.ReadString();
		m_Icon = reader.ReadString();
		m_Action = reader.ReadString();
		m_Desc = reader.ReadString();
		m_TreeType = reader.ReadInt32();
	}
}

//SkillBase.xlsx
public sealed class SkillBaseManager : JW_Table.TableManager<SkillBase>
{
	public const uint VERSION = 2182141379;

	private SkillBaseManager()
	{
	}

	private static readonly SkillBaseManager ms_instance = new SkillBaseManager();

	public static SkillBaseManager instance
	{
		get { return ms_instance; }
	}

	public string source
	{
		get { return "SkillBase.tbl"; }
	}

	public bool Load(string path)
	{
		return Load(path, source, VERSION);
	}

	public bool Load(byte[] buffer)
	{
		return Load(buffer, VERSION, source);
	}

	public SkillBase Find(int key)
	{
		return FindInternal(key);
	}
}
