//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class UnitBase : JW_Table.Binary, JW_Table.IKey
{
	private int m_ID;
	private string m_Name;
	private string m_Prefab;

	public int ID
	{
		get { return m_ID; }
		set { m_ID = value; }
	}

	public string Name
	{
		get { return m_Name; }
		set { m_Name = value; }
	}

	public string Prefab
	{
		get { return m_Prefab; }
		set { m_Prefab = value; }
	}

	public long Key()
	{
		return m_ID;
	}

	public override void Read(JW_Table.Reader reader)
	{
		m_ID = reader.ReadInt32();
		m_Name = reader.ReadString();
		m_Prefab = reader.ReadString();
	}
}

//UnitBase.xlsx
public sealed class UnitBaseManager : JW_Table.TableManager<UnitBase>
{
	public const uint VERSION = 465964783;

	private UnitBaseManager()
	{
	}

	private static readonly UnitBaseManager ms_instance = new UnitBaseManager();

	public static UnitBaseManager instance
	{
		get { return ms_instance; }
	}

	public string source
	{
		get { return "UnitBase.tbl"; }
	}

	public bool Load(string path)
	{
		return Load(path, source, VERSION);
	}

	public bool Load(byte[] buffer)
	{
		return Load(buffer, VERSION, source);
	}

	public UnitBase Find(int key)
	{
		return FindInternal(key);
	}
}
